site_name: UnnyNet Documentation

# Documentation and theme
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: 'img/favicon.ico'

nav:
    - Home: index.md
    - Basic Integration:
      - How to start: basic/basic.md
      - Platforms:
        - Unity3D: basic/integration_unity3d.md
        - JavaScript: basic/integration_javascript.md
        - Android:
          - Basics: basic/integration_android.md
          - Proguard: basic/integration_android_proguard.md
      - Authorization: basic/authorization.md
    - Advanced Integration:
      - Leaderboards: advanced/leaderboards.md
      - Achievements: advanced/achievements.md
      - User: advanced/user.md
      - Real-time Chat: advanced/chat.md
      - Chat Popup: advanced/chat_popup.md
      - Private Channels: advanced/private_channels.md
      - Theme Customization: advanced/themes.md
      - Guilds:
        - Basic Information: advanced/guilds/guilds.md
        - Setup: advanced/guilds/guilds_setup.md
        - Tests: advanced/guilds/guilds_test.md
        - API: advanced/guilds/guilds_api.md
      - Open UnnyNet: advanced/open.md
      - Close UnnyNet: advanced/close.md
      - Set Frame: advanced/setframe.md
    - Data Editor:
      - Basic: data_editor/basic.md
      - Getting Started:
        - How to Launch: data_editor/getting_started/how_to_launch.md
        - Important Terms: data_editor/getting_started/important_terms.md
        - Templates: data_editor/getting_started/templates.md
        - Parameters: data_editor/getting_started/parameters.md
        - Documents: data_editor/getting_started/documents.md
      - Code Generation: data_editor/code_generation.md
      - Example: data_editor/example.md
      - What's next: data_editor/what_next.md
    - Requests:
      - Response Data: requests/response_data.md
      - Get API: requests/get_api.md
    - Release Notes: release_notes.md

extra_css:
  - css/code_tabs.css

extra_javascript:
  - js/main.js

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: False
      guess_lang: False
  - toc:
      permalink: True
  - markdown_fenced_code_tabs:
      single_block_as_tab: False
