site_name: UnnyNet Documentation

# Documentation and theme
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: 'img/favicon.ico'

nav:
    - Home: index.md
    - How does it work: general.md
    - Basic Integration:
      - How to start: basic/basic.md
      - Platforms:
        - Unity3D: basic/integration_unity3d.md
        - Android:
          - Basics: basic/integration_android.md
          - Proguard: basic/integration_android_proguard.md
      - Authorization: basic/authorization.md
    - Advanced Integration: 
      - Leaderboards: advanced/leaderboards.md
      - Achievements: advanced/achievements.md
      - Real-time Chat: advanced/chat.md
      - Theme Customization: advanced/themes.md
      - Guilds:
        - Basic Information: advanced/guilds/guilds.md
        - Setup: advanced/guilds/guilds_setup.md
        - Tests: advanced/guilds/guilds_test.md
        - API: advanced/guilds/guilds_api.md
      - Open UnnyNet: advanced/open.md
      - Close UnnyNet: advanced/close.md
    - Release Notes: release_notes.md

extra_css:
  - css/code_tabs.css

extra_javascript:
  - js/main.js

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: False
      guess_lang: False
  - toc:
      permalink: True
  - markdown_fenced_code_tabs:
      single_block_as_tab: False
