site_name: UnnyNet Documentation

# Documentation and theme
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: 'img/favicon.ico'

nav:
    - Home: index.md
    - Basic Integration:
      - How to start: basic/basic.md
      - Platforms:
        - Unity3D: basic/integration_unity3d.md
      - Authorization: basic/authorization.md
      - Storage: basic/storage.md
      - Payments: basic/payments.md
    - Data Editor:
      - Basic: data_editor/basic.md
      - Getting Started:
        - Important Terms: data_editor/getting_started/important_terms.md
        - Templates: data_editor/getting_started/templates.md
        - Parameters: data_editor/getting_started/parameters.md
        - Documents: data_editor/getting_started/documents.md
      - Code Generation: data_editor/code_generation.md
      - Example: data_editor/example.md
      - What's next: data_editor/what_next.md
    - Requests:
      - Response Data: requests/response_data.md
    - Release Notes: release_notes.md

extra_css:
  - css/code_tabs.css
  - css/pages.css

extra_javascript:
  - js/main.js

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: False
      guess_lang: False
  - toc:
      permalink: True
  - markdown_fenced_code_tabs:
      single_block_as_tab: False

plugins:
  - pdf-export:
      combined: true
  - search
  - awesome-pages