site_name: UnnyNet Documentation

nav:
    - Table of Contents: table.md
    - Home: index.md
    - Video Tutorials: video_tutorials.md
    - Basic Integration:
      - How to start: basic/basic.md
      - Platforms:
        - Unity3D: basic/integration_unity3d.md
      - Authorization: basic/authorization.md
      - Storage: basic/storage.md
      - Payments: basic/payments.md
    - Data Editor:
      - Basic: data_editor/basic.md
      - Getting Started:
        - Important Terms: data_editor/getting_started/important_terms.md
        - Templates: data_editor/getting_started/templates.md
        - Parameters: data_editor/getting_started/parameters.md
        - Documents: data_editor/getting_started/documents.md
        - Enums: data_editor/getting_started/enums.md
      - Deploy: data_editor/deploy.md
      - Code Generation: data_editor/code_generation.md
      - Advanced:
        - Environment: data_editor/advanced/environment.md
        - Localization: data_editor/advanced/localization.md
      - Example: data_editor/example.md
      - What's next: data_editor/what_next.md
    - Requests:
      - Response Data: requests/response_data.md
    - Pricing: pricing.md
    - Release Notes: release_notes.md

extra_css:
  - css/code_tabs.css
  - css/pages.css

extra_javascript:
  - js/main.js

google_analytics:
  - UA-125653723-3
  - auto
