site_name: UnnyNet Documentation
theme: mkdocs
nav:
    - Home: index.md
    - General:
      - How does it work: general/general.md
      - Pricing: general/pricing.md
    - Basic Integration: 
      - How to start: basic/basic.md
      - Platforms:
        - Unity3D: basic/integration_unity3d.md
        - Android: basic/integration_unity3d.md
      - Authorization: basic/authorization.md
    - Advanced Integration: 
      - Leaderboards: advanced/leaderboards.md
      - Achievements: advanced/achievements.md
      - Real-time Chat: advanced/chat.md
      - Guilds:
        - Basic Information: advanced/guilds/guilds.md
        - Setup: advanced/guilds/guilds_setup.md
        - Tests: advanced/guilds/guilds_test.md
        - API: advanced/guilds/guilds_api.md
      - Open UnnyNet: advanced/open.md
    - Release Notes: release_notes.md
