site_name: Balancy Documentation

# Documentation and theme
theme:
  name: 'material'
  custom_dir: 'overrides'
  language: 'ru'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: 'img/favicon.ico'

nav:
    - Table of Contents: table.md
    - Главная: index.md
#    - Видео туториалы: video_tutorials.md
    - Базовая интеграция:
      - С чего начать: basic/basic.md
      - Платформы:
        - Unity3D: basic/integration_unity3d.md
      - Авторизация: basic/authorization.md
      - Платежи: basic/payments.md
    - Data Editor:
      - Базовая информация: data_editor/basic.md
      - С чего начать:
        - Основные понятия: data_editor/getting_started/important_terms.md
        - Шаблоны: data_editor/getting_started/templates.md
        - Параметры: data_editor/getting_started/parameters.md
        - Документы: data_editor/getting_started/documents.md
        - Перечисления: data_editor/getting_started/enums.md
      - Публикация: data_editor/deploy.md
      - Генерация кода: data_editor/code_generation.md
      - Дополнительная информация :
        - Окружения: data_editor/advanced/environment.md
        - Ассеты: data_editor/advanced/assets.md
        - Формат отображения: data_editor/advanced/display_format.md
        - Локализация: data_editor/advanced/localization.md
      - Пример: data_editor/example.md
      - Что дальше: data_editor/what_next.md
      - Дополнительно:
          - Сводка: data_editor/extra/info.md
          - Схема данных: data_editor/extra/data_scheme.md
    - Примеры:
        - Оферы в магазине: examples/store_offers.md
    - Запросы:
      - Формат ответов: requests/response_data.md
    - Цены: pricing.md
    - Примечания к выпускам: release_notes.md

extra_css:
  - css/code_tabs.css
  - css/pages.css

extra_javascript:
  - js/main.js

google_analytics:
  - UA-125653723-3
  - auto

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: False
      guess_lang: False
  - toc:
      permalink: True
  - markdown_fenced_code_tabs:
      single_block_as_tab: False
plugins:
  - pdf-export:
      combined: true
  - search
  - awesome-pages
